# Generated by Django 5.0.3 on 2024-11-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_category_blogspost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogspost',
            name='user_name',
        ),
    ]
