# Generated by Django 5.0.3 on 2024-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_blogspost_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('NEWS', 'NEWS'), ('FASHION', 'FASHION'), ('SPORTS', 'SPORTS')], default='NEWS', max_length=20),
        ),
    ]
